# Generated by Django 4.2.9 on 2024-01-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
