# Generated by Django 4.2.9 on 2024-01-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_delete_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='outstading_amount',
            new_name='outstanding_amount',
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
