# Generated by Django 4.2.9 on 2024-02-23 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0003_client_creator_contract_creator_event_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AlterField(
            model_name='client',
            name='commercial_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
