# Generated by Django 4.2.9 on 2024-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password_set',
            field=models.BooleanField(default=False),
        ),
    ]
