# Generated by Django 4.2.9 on 2024-02-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_employee_password_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group_name',
        ),
    ]
