# Generated by Django 4.2.9 on 2024-05-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group_name',
        ),
    ]
